### PR TITLE
Fix bug: made JSON tag parsing case-insensitive

### LINKED ISSUE #176: Case-insensitive tags parsing for JSON file
Case-insensitive tags should be parsed to the same object.

### PR DESCRIPTION
**Pull request by mmaimer33**
Close #176

### CODE REVIEW

File: src/main/java/arb/storage/JsonAdaptedTag.java [hunk 1]
```diff
@@ -18,7 +18,7 @@ class JsonAdaptedTag {
      */
     @JsonCreator
     public JsonAdaptedTag(String tagName) {
-        this.tagName = tagName;
+        this.tagName = tagName.toLowerCase();
```
Comment (zrei) [inline src/main/java/arb/storage/JsonAdaptedTag.java:21]: Seems alright!

**Review by zrei — APPROVED** [review]
LGTM!
