### PR TITLE
Delete project feature

### LINKED ISSUE #38: Implement delete project feature
- [x] Create DeleteProjectCommand class
- [x] Create DeleteProjectParser class
- [x] Ensure the execution of this command throws an exception if the project list is not currently being shown
- [x] Create tests for parser and command class

### PR DESCRIPTION
**Pull request by mmaimer33**
Close #38

### CODE REVIEW

File: src/main/java/arb/logic/commands/project/DeleteProjectCommand.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    }
+
+    @Override
+    public CommandResult execute(Model model, ListType currentListBeingShown) throws CommandException {
+        requireNonNull(model);
+        List<Project> lastShownList = model.getFilteredProjectList();
+
+        if (targetIndex.getZeroBased() >= lastShownList.size()) {
+            throw new CommandException(Messages.MESSAGE_INVALID_PROJECT_DISPLAYED_INDEX);
+        }
```
Comment (zrei) [inline src/main/java/arb/logic/commands/project/DeleteProjectCommand.java:46]: You should throw an exception here if `currentListBeingShown != ListType.Project`, you can refer to `MarkProjectCommand` or `EditProjectCommand`.

File: src/test/java/arb/logic/parser/project/DeleteProjectCommandParserTest.java [hunk 2]
```diff
@@ -0,0 +1,33 @@
+package arb.logic.parser.project;
```
Comment (zrei) [inline src/test/java/arb/logic/parser/project/DeleteProjectCommandParserTest.java:1]: Good job on the tests!

**Review by zrei — APPROVED** [review]
LGTM!
